// App-wide settings: language (en/es), theme (dark/light), and units
// (imperial/metric), persisted per browser in moto.settings.v1. The theme
// lands as data-theme on <html> so CSS variable overrides do the work.
//
// Two translators, one per kind of text — they scale differently, so they are
// deliberately not the same mechanism:
//
//   t()  — app CHROME (buttons, headings, labels). A finite, stable set, so a
//          dictionary in this file is right. `npm run i18n:check` fails the
//          build when a t() call has no translation, so it cannot drift.
//
//   tt() — trip CONTENT and engine sentences. Unbounded: every new trip, in any
//          country, brings its own prose. So it resolves through
//          i18n/resolve.js, which reads the TRIP'S OWN translation cache first
//          (see i18n/collect.js and the translate flow). Nothing about adding a
//          trip requires touching source.
//
// Place names, road numbers, and addresses stay as-written in both — they have
// to match road signs and GPS.

import React, { createContext, useContext, useEffect, useState } from 'react';
import { resolveContent } from '../i18n/resolve.js';
import { TripContext } from './store.js';

const KEY = 'moto.settings.v1';
// `density` is the Ride Mode HUD's information budget: 'detailed' shows the
// labels and the weather, 'minimal' strips it to numbers only.
// Device-scoped, all of it. Anything that should follow the RIDER rather than
// the phone (home address, food, bike range) lives in engine/profile.js.
const DEFAULTS = {
  lang: 'en', theme: 'dark', units: 'imperial', shields: true, density: 'detailed',
  basemap: 'sat',      // which map the plan screen opens on
  terrain: false,      // 3D relief
  voice: true,         // spoken turn directions in Ride Mode
  speedSign: true,     // posted-limit sign
  keepAwake: true,     // wake lock while riding
  learnPlaces: true,   // record evidence from picks and rejections
};

function load() {
  try { return { ...DEFAULTS, ...JSON.parse(localStorage.getItem(KEY) || '{}') }; } catch { return { ...DEFAULTS }; }
}

const SettingsContext = createContext({ ...DEFAULTS, set: () => {} });

export function SettingsProvider({ children }) {
  const [settings, setSettings] = useState(load);

  useEffect(() => {
    document.documentElement.dataset.theme = settings.theme;
    try { localStorage.setItem(KEY, JSON.stringify(settings)); } catch { /* full */ }
  }, [settings]);

  const set = (patch) => setSettings((s) => ({ ...s, ...patch }));
  return <SettingsContext.Provider value={{ ...settings, set }}>{children}</SettingsContext.Provider>;
}

export const useSettings = () => useContext(SettingsContext);

// ---- chrome dictionary ----
// Keyed by the English string so call sites stay readable: t('Feasibility').
// Missing keys fall back to English rather than breaking the UI.

const ES = {
  // masthead / menu
  'Menu': 'Menú',
  'Trip controls': 'Controles del viaje',
  'New trip': 'Nuevo viaje',
  'Delete current trip': 'Eliminar viaje actual',
  'Save current as scenario': 'Guardar como escenario',
  'Trips': 'Viajes',
  'Scenarios': 'Escenarios',
  'Load': 'Cargar',
  'Feasibility': 'Factibilidad',
  'Budget': 'Presupuesto',
  'Ride': 'Rodar',
  'Undo': 'Deshacer',
  'Export': 'Exportar',
  'Import': 'Importar',
  'Reset': 'Restablecer',
  'Optimizer': 'Optimizador',
  'Hide': 'Ocultar',
  'Packing': 'Equipaje',
  'Settings': 'Ajustes',
  'Map': 'Mapa',
  'Trip': 'Viaje',
  'riders': 'motociclistas',
  'days': 'días',
  // day panel
  'Depart': 'Salida',
  'End': 'Fin',
  'Miles': 'Millas',
  'Ride hrs': 'Hrs en ruta',
  'Stop hrs': 'Hrs parado',
  'Longest fuel gap': 'Mayor tramo sin bencina',
  'Hard constraints': 'Restricciones duras',
  'Constraints': 'Restricciones',
  'notes — the engine grades the Hard gates below': 'notas — el motor evalúa las Puertas duras de abajo',
  'read from the route — suggestions add to it': 'leídas de la ruta — las sugerencias se agregan a ella',
  'not on the route': 'fuera de la ruta',
  'Add to route': 'Agregar a la ruta',
  'stop removed — re-point': 'parada eliminada — reasignar',
  'Route & stops': 'Ruta y paradas',
  'drag ⠿ to reorder · tap to zoom the map · ⓘ for details': 'arrastra ⠿ para reordenar · toca para acercar el mapa · ⓘ para detalles',
  'Conditions': 'Condiciones',
  'Optional modules': 'Módulos opcionales',
  'Food': 'Comida',
  'Photo stops': 'Paradas de foto',
  'Lodging': 'Alojamiento',
  'Operations': 'Operaciones',
  'click ✎ to edit': 'toca ✎ para editar',
  'total': 'total',
  // packing
  'Packing list': 'Lista de equipaje',
  'Per rider — saves on this device only, so each rider checks off their own.': 'Por motociclista — se guarda solo en este dispositivo, cada uno marca la suya.',
  'packed': 'listo',
  'Uncheck all': 'Desmarcar todo',
  'Close': 'Cerrar',
  // settings
  'Language': 'Idioma',
  'English': 'Inglés',
  'Spanish': 'Español',
  'Theme': 'Tema',
  'Dark': 'Oscuro',
  'Light': 'Claro',
  'Applies on this device only. Trip text and AI answers stay in the language they were written in — ask the optimizer in Spanish and it answers in Spanish.': 'Se aplica solo en este dispositivo. El texto del viaje y las respuestas de la IA quedan en el idioma en que fueron escritos — pregúntale al optimizador en español y responde en español.',
  'Account session and backup status.': 'Sesión de cuenta y estado de la copia de seguridad.',
  'Places used by the planner and trip shortcuts.': 'Lugares que usa el planificador y accesos rápidos del viaje.',
  'Bike profile, route style, and trip preferences.': 'Perfil de moto, estilo de ruta y preferencias del viaje.',
  'Theme, language, and units for this screen.': 'Tema, idioma y unidades para esta pantalla.',
  'Map render defaults and overlays.': 'Valores predeterminados del mapa y superposiciones.',
  'Live navigation behavior while you are riding.': 'Comportamiento de navegación en vivo mientras estás rodando.',
  'Shared-trip setup and rider status.': 'Configuración del viaje compartido y estado de los participantes.',
  'Learning signals and local cache controls.': 'Señales de aprendizaje y controles de caché local.',
  'Product information, credits, and diagnostics.': 'Información del producto, créditos y diagnósticos.',
  // misc chrome
  'Feasibility studies': 'Estudios de factibilidad',
  'The whole trip at a glance': 'El viaje completo de un vistazo',
  'nights': 'noches',
  // settings (units)
  'Units': 'Unidades',
  // trip translation
  'Trip text': 'Texto del viaje',
  'translated': 'traducido',
  'Retry': 'Reintentar',
  'Trip text translates itself when you pick a language, and is stored on the trip so it travels with export and import. Retry is only needed if a run was interrupted.': 'El texto del viaje se traduce solo al elegir un idioma, y queda guardado en el viaje, así que viaja con la exportación y la importación. Reintentar solo hace falta si una pasada quedó a medias.',
  "Sends this trip's text to the optimizer for translation and stores the result on the trip, so it travels with export and import. Place names, road numbers and addresses are left as written.": 'Envía el texto de este viaje al optimizador para traducirlo y guarda el resultado en el viaje, así viaja con exportar e importar. Los nombres de lugares, números de ruta y direcciones se dejan como están.',
  'Imperial (mi, °F)': 'Imperial (mi, °F)',
  'Metric (km, °C)': 'Métrico (km, °C)',
  'You have left the shared trip. Your copy stays on this device.': 'Has salido del viaje compartido. Tu copia se queda en este dispositivo.',
  // install prompt
  'Install Roadbook': 'Instalar Roadbook',
  'Add Roadbook to your Home Screen': 'Agrega Roadbook a tu pantalla de inicio',
  'Full-screen, offline, and Ride Mode keeps the screen awake — a tab cannot do that.': 'A pantalla completa, sin conexión, y el modo Ruta mantiene la pantalla encendida; una pestaña no puede hacerlo.',
  'Tap the Share button — the square with the arrow — at the bottom of Safari': 'Toca el botón Compartir (el cuadrado con la flecha) en la parte inferior de Safari',
  'Scroll down and tap “Add to Home Screen”': 'Desplázate hacia abajo y toca “Añadir a pantalla de inicio”',
  'Tap “Add” — Roadbook opens full-screen from your Home Screen': 'Toca “Añadir”: Roadbook se abre a pantalla completa desde tu pantalla de inicio',
  'Tap the ⋯ menu at the top right': 'Toca el menú ⋯ arriba a la derecha',
  'Tap “Share”, then scroll down to “Add to Home Screen”': 'Toca “Compartir” y baja hasta “Añadir a pantalla de inicio”',
  'Tap the ⋮ menu at the top right of the browser': 'Toca el menú ⋮ arriba a la derecha del navegador',
  'Tap “Add to Home screen” or “Install app”': 'Toca “Añadir a pantalla de inicio” o “Instalar app”',
  'Confirm — Roadbook opens full-screen from your Home Screen': 'Confirma: Roadbook se abre a pantalla completa desde tu pantalla de inicio',
  'Look for the install icon at the right end of the address bar': 'Busca el icono de instalar en el extremo derecho de la barra de direcciones',
  'Or open the browser menu and choose “Install Roadbook”': 'O abre el menú del navegador y elige “Instalar Roadbook”',
  'Install': 'Instalar',
  'Not now': 'Ahora no',
  'Ride Mode': 'Modo Ruta',
  'I understand — start navigation': 'Entendido — iniciar navegación',
  // ride quick-add
  'Nothing ahead on this road.': 'No hay nada adelante en esta carretera.',
  'One option ahead': 'Una opción adelante',
  'options ahead': 'opciones adelante',
  'More options…': 'Más opciones…',
  'Looking ahead…': 'Buscando adelante…',
  'Added': 'Agregado',
  // quick ride
  'Ride somewhere now': 'Rodar a algún lugar ahora',
  'One destination from where you are — turn-by-turn on the roads you actually want.': 'Un destino desde donde estás, con guía paso a paso por las carreteras que realmente quieres.',
  'Finding you…': 'Buscándote…',
  'Where to?': '¿A dónde?',
  'Could not get your location. Allow location access, or set a home place in Settings → Places.': 'No se pudo obtener tu ubicación. Permite el acceso a la ubicación o define un lugar de casa en Ajustes → Lugares.',
  'Quick rides': 'Rodadas rápidas',
  'one-day rides from where you were — ride again, or make one a trip': 'rodadas de un día desde donde estabas: repítelas o convierte una en viaje',
  'Make it a trip': 'Convertir en viaje',
  // minimal day header
  'Day options': 'Opciones del día',
  'Phase': 'Fase',
  'Where this day is tight, what breaks, what to change': 'Dónde este día va justo, qué falla, qué cambiar',
  'Compare 2–3 bundles of roads and stops, measured': 'Compara 2–3 combinaciones de carreteras y paradas, medidas',
  'Download GPX': 'Descargar GPX',
  'This day as a route for a Garmin or another nav app': 'Este día como ruta para un Garmin u otra app de navegación',
  'Advanced': 'Avanzado',
  'pace · absolute range · MPG · dusk · calendar UTC offset': 'ritmo · autonomía absoluta · MPG · anochecer · desfase UTC del calendario',
  // nearby picker
  'Fills the gap': 'Cubre el tramo',
  'Still leaves': 'Aún deja',
  'past your': 'más allá de tu',
  'range': 'autonomía',
  'Say fuel, food, coffee or help.': 'Di gasolina, comida, café o ayuda.',
  'Listening — say fuel, food, coffee or help': 'Escuchando: di gasolina, comida, café o ayuda',
  'Tap to speak': 'Toca para hablar',
  'Breaks': 'Rompe',
  'by': 'por',
  'to spare': 'de margen',
  'Kind of food': 'Tipo de comida',
  'Any': 'Cualquiera',
  'Diner': 'Diner',
  'Breakfast': 'Desayuno',
  'Burgers': 'Hamburguesas',
  'BBQ': 'BBQ',
  'Pizza': 'Pizza',
  'Mexican': 'Mexicana',
  'Steak': 'Carnes',
  'Seafood': 'Mariscos',
  'Bar & grill': 'Bar & grill',
  'Italian': 'Italiana',
  'Chinese': 'China',
  'Sandwiches': 'Sándwiches',
  'from this stop': 'desde esta parada',
  'Add a stop to this day': 'Agregar una parada a este día',
  'Add ahead': 'Agregar adelante',
  'Add as fuel stop': 'Agregar como parada de gasolina',
  'Add to the day': 'Agregar al día',
  'Along route': 'En la ruta',
  'Closed at your ETA': 'Cerrado a tu hora de llegada',
  'Closed now': 'Cerrado ahora',
  'Detour not measurable right now': 'No se puede medir el desvío ahora',
  'Find a place': 'Buscar un lugar',
  'Find a place — fuel, food, sights…': 'Buscar un lugar: gasolina, comida, lugares…',
  'Hours': 'Horario',
  'Maps': 'Maps',
  'Measuring the detour…': 'Midiendo el desvío…',
  'Narrow it down — a name, a town…': 'Afina la búsqueda: un nombre, un pueblo…',
  'Near here': 'Cerca de aquí',
  'Map area': 'Zona del mapa',
  'Checking the listing…': 'Consultando la ficha…',
  'Details': 'Detalles',
  'Reviews': 'Reseñas',
  'More reviews': 'Más reseñas',
  'Place facts, photos and reviews from Google': 'Datos, fotos y reseñas del lugar de Google',
  'Dine-in': 'Para comer allí', 'Takeout': 'Para llevar', 'Delivery': 'A domicilio', 'Reservations': 'Reservas',
  'Breakfast': 'Desayuno', 'Lunch': 'Almuerzo', 'Dinner': 'Cena', 'Coffee': 'Café',
  'Outdoor seating': 'Mesas al aire libre', 'Live music': 'Música en vivo', 'Good for groups': 'Bueno para grupos',
  'Dogs OK': 'Admite perros', 'Restroom': 'Baño', 'Kids': 'Niños',
  'Wheelchair entrance': 'Entrada accesible', 'Wheelchair parking': 'Estacionamiento accesible', 'Wheelchair restroom': 'Baño accesible',
  'Free parking': 'Estacionamiento gratis', 'Paid parking': 'Estacionamiento de pago', 'Cards': 'Tarjetas', 'Cash only': 'Solo efectivo', 'NFC pay': 'Pago sin contacto',
  'Go': 'Vamos',
  'Describe riders, days, region and pace — or just type a place name to ride there.': 'Describe motos, días, región y ritmo — o escribe el nombre de un lugar para ir allí.',
  'the long way home from the rally': 'el camino largo a casa desde el rally',
  'place it': 'ubícalo',
  'placed': 'ubicado',
  'A scenic spot the planner placed on the map — no listing names it. Confirm the pin before you ride.': 'Un punto escénico que el planificador ubicó en el mapa — ninguna ficha lo nombra. Confirma el pin antes de salir.',
  'A spot placed on the map on purpose — not a listed business.': 'Un punto ubicado en el mapa a propósito — no es un negocio registrado.',
  'Plan a trip with AI': 'Planear un viaje con IA',
  'Ride now': 'Salir ahora',
  'Ride here': 'Ir hasta aquí',
  'Add to a trip': 'Agregar a un viaje',
  'Search a place, or describe a ride': 'Busca un lugar o describe una salida',
  'Plan this ride with AI': 'Planear esta salida con IA',
  'Plan a trip to': 'Planear un viaje a',
  'with AI': 'con IA',
  'Or keep typing a sentence — riders, days, pace — and the builder opens with it.': 'O sigue escribiendo una frase — motos, días, ritmo — y el planificador se abre con ella.',
  'Searching…': 'Buscando…',
  'Recent': 'Recientes',
  'Show': 'Ver',
  'Near you': 'Cerca de ti',
  'Near': 'Cerca de',
  'from you': 'de ti',
  'Show the map': 'Ver el mapa',
  'Show more': 'Ver más',
  'Show the list': 'Ver la lista',
  'Show the place': 'Ver el lugar',
  'Add': 'Agregar',
  'to…': 'a…',
  'It lands by route order on the day you pick': 'Se coloca en orden de ruta en el día que elijas',
  'Nearest day': 'Día más cercano',
  'from a stop': 'de una parada',
  'New trip with AI that includes this place': 'Nuevo viaje con IA que incluya este lugar',
  'A ride that includes': 'Una salida que incluya',
  'Back': 'Atrás',
  'Photo': 'Foto',
  'Today': 'Hoy',
  'Listing': 'Ficha a',
  'from the pin': 'del pin',
  'Place facts and photo from Google': 'Datos y foto del lugar de Google',
  'No listing found here — it will be added as an unverified stop.': 'No hay ficha aquí — se añadirá como parada sin verificar.',
  'Verified': 'Verificado',
  'Add to this day': 'Agregar a este día',
  'Pick a day to add it': 'Elige un día para añadirlo',
  'Unnamed place': 'Lugar sin nombre',
  'Search this area': 'Buscar en esta zona',
  'Near me': 'Cerca de mí',
  'North up': 'Norte arriba',
  'Frame my trips': 'Encuadrar mis viajes',
  'Route': 'Ruta',
  'Current location': 'Ubicación actual',
  'From': 'Desde',
  'To': 'Hasta',
  'Pick a start': 'Elige un inicio',
  'Pick a destination': 'Elige un destino',
  'Change start': 'Cambiar inicio',
  'Change destination': 'Cambiar destino',
  'Search a place': 'Buscar un lugar',
  'A place on the map, not a listed business — it will be added as a placed pin.': 'Un lugar del mapa, no un negocio con ficha — se añadirá como pin colocado.',
  'Add as photo stop': 'Añadir como parada de fotos',
  'Nothing found — try another chip or add the town name.': 'Nada encontrado: prueba otra categoría o agrega el nombre del pueblo.',
  'Open at your ETA': 'Abierto a tu hora de llegada',
  'Open now': 'Abierto ahora',
  'Place facts from Google': 'Datos del lugar de Google',
  'e.g. 2020 Gold Wing': 'p. ej. Gold Wing 2020',
  'Search any place…': 'Buscar cualquier lugar…',
  'Search is not available right now.': 'La búsqueda no está disponible ahora.',
  'Swap': 'Cambiar',
  'Swap for another place': 'Cambiar por otro lugar',
  'Swap this stop for another place': 'Cambiar esta parada por otro lugar',
  'Swap this stop for…': 'Cambiar esta parada por…',
  'Use this instead': 'Usar este en su lugar',
  'Where to look': 'Dónde buscar',
  'behind you': 'detrás de ti',
  'detour on the way to the next stop': 'de desvío hacia la siguiente parada',
  'Coffee': 'Café',
  'Sights': 'Lugares',
  'Moto': 'Moto',
  'Help': 'Ayuda',
  // templates
  'Your templates': 'Tus plantillas',
  'saved starting points — copy one, or lay its days into a trip': 'puntos de partida guardados: copia una o inserta sus días en un viaje',
  'Template': 'Plantilla',
  'Use it →': 'Usarla →',
  'Delete this template': 'Eliminar esta plantilla',
  'Delete this template?': '¿Eliminar esta plantilla?',
  'trips already made from it are untouched.': 'los viajes ya creados a partir de ella no se tocan.',
  'Save as template': 'Guardar como plantilla',
  'Save as a template': 'Guardar como plantilla',
  'Save template': 'Guardar plantilla',
  'Name this template': 'Nombra esta plantilla',
  'e.g. Sturgis — early exit from Red Lodge': 'p. ej. Sturgis — salida anticipada desde Red Lodge',
  'Reuse this plan for another trip, or share the file with a friend.': 'Reutiliza este plan en otro viaje o comparte el archivo con un amigo.',
  'Days from a template': 'Días de una plantilla',
  'Insert before': 'Insertar antes de',
  'End of the trip': 'Final del viaje',
  'Insert': 'Insertar',
  'Back': 'Atrás',
  'day': 'día',
  // how-to guide
  'Guide': 'Guía',
  'Guide chapters': 'Capítulos de la guía',
  'How to use Roadbook': 'Cómo usar Roadbook',
  'Nothing in the guide matches that.': 'Nada en la guía coincide con eso.',
  'Open the guide →': 'Abrir la guía →',
  'Search the guide': 'Buscar en la guía',
  'See how it works →': 'Ver cómo funciona →',
  'Step-by-step directions and walkthrough videos': 'Instrucciones paso a paso y videos explicativos',
  'Step-by-step directions for every part of the app, with walkthrough videos.': 'Instrucciones paso a paso para cada parte de la app, con videos explicativos.',
  'Walkthrough video coming soon': 'Video explicativo próximamente',
  'Worth knowing': 'Vale la pena saber',
  // overview panel
  'Days': 'Días',
  'drag to reorder': 'arrastra para reordenar',
  'press & hold to reorder': 'mantén presionado para reordenar',
  'grab ⠿ to reorder': 'usa ⠿ para reordenar',
  'Reorder this day': 'Reordenar este día',
  'Add day': 'Agregar día',
  'Trip settings': 'Configuración del viaje',
  'Trip name': 'Nombre del viaje',
  'Trip summary': 'Resumen del viaje',
  'Route character': 'Carácter de la ruta',
  'One choice for every day and every reroute': 'Una opción para cada día y cada desvío',
  'Preview the impact before it touches the trip': 'Previsualiza el impacto antes de cambiar el viaje',
  'Valhalla motorcycle': 'Valhalla para motos',
  'Quick': 'Rápida',
  'Touring': 'Turismo',
  'Back roads': 'Carreteras secundarias',
  'Favors the fastest practical roads, including highways.': 'Favorece las rutas prácticas más rápidas, incluidas las autopistas.',
  'Balances highway progress with good motorcycle roads.': 'Equilibra el avance por autopista con buenas rutas para motos.',
  'Strongly favors secondary roads. Expect longer days.': 'Favorece mucho las carreteras secundarias. Espera días más largos.',
  'Avoid toll roads': 'Evitar carreteras de peaje',
  'Draft route comparison': 'Comparación de ruta en borrador',
  'Nothing is saved until you choose how Roadbook should handle the stops.': 'Nada se guarda hasta que elijas cómo debe tratar Roadbook las paradas.',
  'Testing every day against the new road character': 'Probando cada día con el nuevo carácter de ruta',
  'Current stops stay in place while Valhalla measures the alternate roads.': 'Las paradas actuales permanecen en su lugar mientras Valhalla mide las rutas alternativas.',
  'The comparison could not finish': 'No se pudo terminar la comparación',
  'Try again': 'Intentar de nuevo',
  'Route impact': 'Impacto de la ruta',
  'Riding time': 'Tiempo de conducción',
  'before': 'antes',
  'commitments locked': 'compromisos fijos',
  'booked stays': 'alojamientos reservados',
  'timed commitments': 'compromisos con horario',
  'route stops held': 'paradas de ruta conservadas',
  'What changes': 'Qué cambia',
  'days affected': 'días afectados',
  'The measured day shapes stay effectively the same.': 'La forma medida de los días se mantiene prácticamente igual.',
  'Trip checks': 'Comprobaciones del viaje',
  'new warnings': 'alertas nuevas',
  'No new fuel, duration, or continuity warnings.': 'No hay alertas nuevas de combustible, duración ni continuidad.',
  'place records need a corridor check': 'lugares necesitan revisar su encaje en el corredor',
  'These restaurant or lodging records are not route pins. Booked stays remain locked; Roadbook can align them precisely and research replacements only for flexible places.': 'Estos restaurantes o alojamientos no son puntos de la ruta. Los alojamientos reservados quedan fijos; Roadbook puede alinearlos con precisión y buscar alternativas solo para los lugares flexibles.',
  'Find better-fit stops': 'Buscar paradas que encajen mejor',
  'Keep every stop': 'Conservar todas las paradas',
  'Proposed route': 'Ruta propuesta',
  'dates stay pinned to the calendar': 'las fechas quedan fijas al calendario',
  'Start date': 'Fecha de inicio',
  'Range: comfort mi': 'Rango cómodo (mi)',
  'Range: absolute mi': 'Rango absoluto (mi)',
  'MPG': 'MPG',
  'Ride pack': 'Kit de ruta',
  'GPX — full trip': 'GPX — viaje completo',
  'Calendar (.ics)': 'Calendario (.ics)',
  'GPX loads into Garmin, Rever, or any nav app (per-day GPX is on each day panel).': 'El GPX se carga en Garmin, Rever o cualquier app de navegación (el GPX por día está en el panel de cada día).',
  'The calendar file drops all 11 days — departures, gates, dinners — into everyone\'s phone in Mountain Time.': 'El archivo de calendario deja los 11 días — salidas, cortes, cenas — en el teléfono de todos, en hora de la Montaña.',
  'Road status & smoke': 'Estado de rutas y humo',
  'check the week of': 'revisar la semana del viaje',
  'Reserve these now': 'Reservar esto ahora',
  'open': 'pendientes',
  'Field notes': 'Notas de campo',
  'Fuel discipline': 'Disciplina de bencina',
  'Intercom': 'Intercomunicador',
  'Cash & passes': 'Efectivo y pases',
  'Altitude': 'Altitud',
  'Emergency': 'Emergencia',
  'Rider roster': 'Nómina de motociclistas',
  'name + bike, saved on the trip': 'nombre + moto, se guarda en el viaje',
  'Rider name': 'Nombre',
  'Bike': 'Moto',
  'Add rider': 'Agregar motociclista',
  'Choose a bike…': 'Elegir moto…',
  'marks the': 'marca los',
  'anchor day': 'día ancla',
  'anchor days': 'días ancla',
  'everything else is built around — if a day has to be trimmed, trim anywhere else first.': 'en torno a los que se arma todo lo demás — si hay que recortar un día, recorta primero en cualquier otro.',
  'Drag days to restructure': 'Arrastra los días para reestructurar',
  'Press and hold a day to restructure': 'Mantén presionado un día para reestructurar',
  '— dates stay pinned to the calendar; content moves.': '— las fechas quedan fijas al calendario; el contenido se mueve.',
  // feasibility panel
  'Engine-computed · routed miles · timed stop-by-stop': 'Calculado por el motor · millas ruteadas · cronometrado parada a parada',
  'Feasibility study': 'Estudio de factibilidad',
  'overall': 'general',
  'routed': 'ruteadas',
  'Day by day': 'Día a día',
  '◎ How to break this loop': '◎ Cómo cortar este circuito',
  '✂ Where to split this day': '✂ Dónde dividir este día',
  'Have the optimizer restructure it →': 'Que el optimizador lo reestructure →',
  'Saved permutations': 'Permutaciones guardadas',
  'None yet. Use “Save scenario” in the top bar — or ask the optimizer to rebuild the trip and save the result — then compare permutations here and swap between them.': 'Todavía no hay. Usa «Guardar escenario» en la barra superior — o pídele al optimizador que rearme el viaje y guarde el resultado — y compara las permutaciones aquí.',
  'Plan (col)': 'Plan',
  'Miles (col)': 'Millas',
  'Feas.': 'Fact.',
  'Current working plan': 'Plan de trabajo actual',
  'Method: departure times from each day\'s plan, routed leg durations (OSRM, +15% group pace), planned time-on-ground at every stop, checked against the trip\'s hard gates, its configured fuel range, daylight (~8:30 PM), and booking status. Scenario rows use cached routing where available and planned mileage otherwise.': 'Método: horas de salida del plan de cada día, duraciones de tramos ruteados (OSRM, +15% por ritmo de grupo), tiempo en tierra planificado en cada parada, contrastado con los cortes duros del viaje, su rango de bencina configurado, la luz de día (~8:30 PM) y el estado de las reservas. Las filas de escenarios usan ruteo en caché cuando existe y millaje planificado si no.',
  // budget panel
  'Assumptions': 'Supuestos',
  'Gas $/gal': 'Bencina $/galón',
  'Lodging $/night/rider': 'Alojamiento $/noche/persona',
  'Food $/day/rider': 'Comida $/día/persona',
  'Tickets $/rider': 'Entradas $/persona',
  'Misc $/rider': 'Varios $/persona',
  'Fuel by day': 'Bencina por día',
  'Day (col)': 'Día',
  'Gal/bike': 'Gal/moto',
  '$/rider': '$/persona',
  '$ group': '$ grupo',
  'Per-rider total': 'Total por persona',
  'Fuel': 'Bencina',
  'Lodging (row)': 'Alojamiento',
  'Food (row)': 'Comida',
  'Tickets (Buffalo Chip, museums, passes)': 'Entradas (Buffalo Chip, museos, pases)',
  'Misc / buffer': 'Varios / colchón',
  'Total per rider': 'Total por persona',
  // chat panel
  'Proposed changes': 'Cambios propuestos',
  'saves as': 'se guarda como',
  'Apply': 'Aplicar',
  'Dismiss': 'Descartar',
  'Ask, or tell me to rework the trip…': 'Pregunta, o pídeme que rearme el viaje…',
  'Send': 'Enviar',
  'Thinking…': 'Pensando…',
  // detail modal / misc
  'Open this day': 'Abrir este día',
  'Close (btn)': 'Cerrar',
  'Add a stop here — name it:': 'Agregar una parada aquí — ponle nombre:',
  'Add a stop': 'Agregar una parada',
  // the route sheet and the add-a-stop face (Sep 20, 2026)
  'Your route': 'Tu ruta',
  'Show the route': 'Mostrar la ruta',
  'Riding a different road than the plan — the trip is unchanged.': 'Vas por una carretera distinta a la del plan: el viaje no cambia.',
  'Toll road': 'Carretera de peaje',
  'tolls': 'de peaje',
  'toll estimated for this corridor': 'peaje estimado para este corredor',
  'Route options': 'Opciones de ruta',
  'Add a stop to your route': 'Agrega una parada a tu ruta',
  'Remove this stop': 'Quitar esta parada',
  'Swap start and destination': 'Intercambiar inicio y destino',
  'Measuring the roads…': 'Midiendo las carreteras…',
  'No road found between those points right now.': 'No se encontró ninguna carretera entre esos puntos en este momento.',
  'There is one road worth riding between these points.': 'Hay una sola carretera que vale la pena entre estos puntos.',
  'Fastest': 'La más rápida',
  'Shortest': 'La más corta',
  'Checking traffic…': 'Consultando el tráfico…',
  'Checking traffic for your departure…': 'Consultando el tráfico para tu salida…',
  'riding in traffic': 'de marcha con tráfico',
  'over the free-flowing road': 'más que la carretera sin tráfico',
  'the road is clear at this hour': 'la carretera está despejada a esa hora',
  'predicted for': 'previsto para',
  'in traffic': 'con tráfico',
  "Predicted for each day's own departure": 'Previsto para la salida de cada día',
  'Predicted traffic on this departure': 'Tráfico previsto en esta salida',
  'in traffic right now': 'con el tráfico actual',
  'Traffic is clear right now': 'El tráfico está despejado ahora',
  'Free-flowing road time — no live traffic': 'Tiempo sin tráfico: no hay datos de tráfico en vivo',
  'Choose on map': 'Elegir en el mapa',
  'Search along route': 'Buscar a lo largo de la ruta',
  'Search by voice': 'Buscar por voz',
  'Add stop': 'Agregar parada',
  'What is here?': '¿Qué hay aquí?',
  'e.g. Palisades Parkway': 'p. ej. Palisades Parkway',
  'Via': 'Punto de paso',
  'Shell': 'Contenedor',
  'Favorite': 'Favorito',
  'Work': 'Trabajo',
  'Home': 'Casa',
  'Food per day': 'Comida por día',
  'Fuel per gallon': 'Combustible por galón',
  'Lodging per night': 'Alojamiento por noche',
  'Used by the budget estimate. Fuel comes from your bike’s economy above, so only the price is needed here.': 'Lo usa la estimación de presupuesto. El combustible sale del consumo de tu moto de arriba, así que aquí solo hace falta el precio.',
  'What a day costs': 'Lo que cuesta un día',
  'Bike specs': 'Especificaciones de la moto',
  'Custom bike': 'Moto personalizada',
  'Add your own bike': 'Agregar tu propia moto',
  'Bike name': 'Nombre de la moto',
  'Powertrain': 'Tren motriz',
  'Gas': 'Gasolina',
  'Electric': 'Eléctrica',
  'Add this bike': 'Agregar esta moto',
  'Tank (gal)': 'Depósito (gal)',
  'Claimed range (mi)': 'Autonomía declarada (mi)',
  'Change': 'Cambiar',
  'Not in the catalog — set your tank size and economy below and the range follows from those.': 'No está en el catálogo: indica abajo el tamaño del depósito y el consumo, y la autonomía sale de ahí.',
  'Range below was worked out from the tank and economy above, keeping a 20% reserve. Change either figure if yours differs.': 'La autonomía de abajo se calculó con el depósito y el consumo de arriba, dejando un 20% de reserva. Cambia cualquiera de las dos cifras si la tuya es distinta.',
  'Range below was worked out from the claimed range above, keeping a 20% reserve. Change that figure if yours differs.': 'La autonomía de abajo se calculó con la autonomía declarada de arriba, dejando un 20% de reserva. Cambia esa cifra si la tuya es distinta.',
  'What do you ride?': '¿Qué moto llevas?',
  'Your bike': 'Tu moto',
  'e.g. Road Glide, R 1250 GS, Gold Wing': 'p. ej. Road Glide, R 1250 GS, Gold Wing',
  'gal': 'gal',
  'mi claimed range': 'mi de autonomía declarada',
  'mpg loaded': 'mpg cargada',
  'your figures': 'tus cifras',
  '3D terrain': 'Relieve 3D',
  'Absolute range': 'Autonomía máxima',
  'Also treated as a requirement — say it here and the planner routes and picks around it.': 'También se trata como requisito: dilo aquí y el planificador traza la ruta y elige evitándolo.',
  'Announcements at one mile, a quarter mile, and the turn. Ride Mode’s mute button still overrides this for one ride.': 'Avisos a una milla, a un cuarto de milla y en el giro. El botón de silencio del Modo Ruta sigue mandando durante ese trayecto.',
  'Anything else': 'Algo más',
  'Avoid': 'Evitar',
  'Avoid tolls': 'Evitar peajes',
  'Back roads — avoid highways': 'Carreteras secundarias — evitar autopistas',
  'Cached routes and turn-by-turn. Clearing them costs nothing but a re-route next time the trip is opened — your trips are not touched.': 'Rutas y navegación en caché. Borrarlas solo cuesta un recálculo la próxima vez que abras el viaje; tus viajes no se tocan.',
  'Clear cached routes': 'Borrar rutas en caché',
  'Comfortable range': 'Autonomía cómoda',
  'Default basemap': 'Mapa base predeterminado',
  'Dietary needs': 'Necesidades alimentarias',
  'HUD density': 'Densidad del HUD',
  'Hillshaded relief from open elevation data. Costs a little battery on a phone.': 'Relieve sombreado con datos de elevación abiertos. Consume algo de batería en el móvil.',
  'Interests': 'Intereses',
  'Keep the screen awake': 'Mantener la pantalla encendida',
  'Keeps tolled bridges and tunnels out of every route': 'Mantiene puentes y túneles de peaje fuera de cada ruta',
  'Kept on this device — the account copy could not be reached.': 'Guardado en este dispositivo: no se pudo acceder a la copia de la cuenta.',
  'Kept on this device.': 'Guardado en este dispositivo.',
  'Kind of place': 'Tipo de lugar',
  'Learn from my choices': 'Aprender de mis elecciones',
  'Max hours in a day': 'Horas máximas por día',
  'Measure': 'Medir',
  'Minimal': 'Mínima',
  'Minimal sheds the labels and the weather chip and leaves the numbers.': 'La mínima quita las etiquetas y el clima y deja los números.',
  'No home address yet — add one and the builder can start a trip from it.': 'Aún no hay dirección de casa: añade una y el constructor podrá empezar un viaje desde ahí.',
  'Not measured yet': 'Sin medir todavía',
  'Off stops new evidence being recorded. It does not delete what is already there.': 'Desactivado deja de registrar nuevas señales. No borra lo que ya existe.',
  'Posted speed limit': 'Límite de velocidad señalizado',
  'Quick — highways welcome': 'Rápido — autopistas bienvenidas',
  'Range is your bike’s, in the units above. The comfort figure is what fuel warnings grade against; absolute is what the engine treats as a hard limit.': 'La autonomía es la de tu moto, en las unidades de arriba. La cifra cómoda es la que evalúan los avisos de combustible; la máxima es el límite duro del motor de cálculo.',
  'Read from OpenStreetMap where the road carries a limit. Hidden where it does not — it is never a guess.': 'Se lee de OpenStreetMap donde la vía tiene límite. Se oculta donde no lo tiene: nunca es una suposición.',
  'Real route signage drawn on the road you are on, over the basemap.': 'Señalización real de carretera dibujada sobre la vía por la que vas, encima del mapa base.',
  'Remove': 'Quitar',
  'Riding': 'Conducción',
  'Roads': 'Carreteras',
  'Saved places give the planner real coordinates. Say “start at home” and it uses this address instead of guessing.': 'Los lugares guardados dan coordenadas reales al planificador. Di «salir de casa» y usará esta dirección en vez de adivinar.',
  'Saved to your account.': 'Guardado en tu cuenta.',
  'Search for the address': 'Busca la dirección',
  'Selecting an option, replacing a stop, and confirming a trip teach Roadbook which kinds of places you like. It stores the Google place id and a broad tag — never ratings, addresses or hours.': 'Elegir una opción, reemplazar una parada y confirmar un viaje le enseñan a Roadbook qué tipo de lugares te gustan. Guarda el id de lugar de Google y una etiqueta general; nunca valoraciones, direcciones ni horarios.',
  'Sign in and your places and preferences travel with you.': 'Inicia sesión y tus lugares y preferencias te acompañan.',
  'Spoken directions': 'Indicaciones habladas',
  'Storage on this device': 'Almacenamiento en este dispositivo',
  'These seed every new trip and ride into what the AI proposes. Any single trip can still be changed on its own without touching these.': 'Estos valores inician cada viaje nuevo y alimentan lo que propone la IA. Cualquier viaje concreto se puede cambiar por su cuenta sin tocar esto.',
  'Touring — balanced': 'Turismo — equilibrado',
  'Treated as a hard requirement, not a preference — the planner will not propose a stop that cannot feed you.': 'Se trata como requisito estricto, no como preferencia: el planificador no propondrá una parada que no pueda darte de comer.',
  'Usual departure': 'Salida habitual',
  'Usual riders': 'Motoristas habituales',
  'What a good stop looks like to you.': 'Cómo es para ti una buena parada.',
  'What this app has learned': 'Lo que ha aprendido esta app',
  'What you stop for': 'Por qué paras',
  'Which map the plan screen opens on. The switcher on the map still changes it for the session.': 'Con qué mapa se abre la pantalla de planificación. El selector del mapa sigue cambiándolo durante la sesión.',
  'e.g. 1500 Harbor Blvd, Weehawken NJ': 'p. ej. 1500 Harbor Blvd, Weehawken NJ',
  'e.g. covered parking, cheap and clean, camping': 'p. ej. aparcamiento cubierto, barato y limpio, camping',
  'e.g. diner breakfast, BBQ, local seafood': 'p. ej. desayuno de diner, barbacoa, marisco local',
  'e.g. interstates, gravel, big cities': 'p. ej. autopistas interestatales, grava, ciudades grandes',
  'e.g. twisty roads, hot springs, history, national parks': 'p. ej. carreteras con curvas, aguas termales, historia, parques nacionales',
  'e.g. two-up on a loaded bagger, so no gravel and shorter days after 4pm': 'p. ej. dos personas en una bagger cargada, así que nada de grava y días más cortos a partir de las 16:00',
  'e.g. vegetarian, gluten free': 'p. ej. vegetariano, sin gluten',
  'navigation sets': 'juegos de navegación',
  'no limit': 'sin límite',
  'routed days': 'días con ruta',
  'off route': 'fuera de ruta',
  '✓ to place': '✓ para colocar',
  'Drag onto the road you want': 'Arrastra hasta la carretera que quieres',
  'Add a stop — search any real place (e.g. \'Wall Drug, SD\')…': 'Agregar una parada — busca cualquier lugar real (p. ej. \'Wall Drug, SD\')…',
  'Click for details': 'Clic para ver detalles',
  'Click for the stop card': 'Clic para ver la ficha de la parada',
  'Edit stop': 'Editar parada',
  'A spot you placed on the map — not a listed business. It rides as a deliberate pin.': 'Un punto que ubicaste en el mapa — no es un negocio registrado. Viaja como un pin deliberado.',
  'Dropped pin': 'Pin colocado',
  'Use this spot': 'Usar este punto',
  'Add this spot to the day': 'Agregar este punto al día',
  'drag the pin to adjust': 'arrastra el pin para ajustar',
  '✓ to use it': '✓ para usarlo',
  '✓ to add it': '✓ para agregarlo',
  // day panel details
  'Tonight': 'Esta noche',
  'lodging': 'alojamiento',
  '● Confirmed booking': '● Reserva confirmada',
  '▲ Not yet booked — reserve now': '▲ Sin reservar — reservar ahora',
  '○ No lodging set': '○ Sin alojamiento definido',
  'Nothing planned yet': 'Nada planificado aún',
  '✎ edit': '✎ editar',
  'Property / plan': 'Propiedad / plan',
  'none': 'ninguno',
  'needs booking': 'falta reservar',
  'booked': 'reservado',
  'Address / town': 'Dirección / pueblo',
  'Note': 'Nota',
  'Spot': 'Lugar',
  'Where': 'Dónde',
  'Cancel': 'Cancelar',
  'breakfast': 'desayuno',
  'lunch': 'almuerzo',
  'dinner': 'cena',
  'Remove this day': 'Eliminar este día',
  // day description + drift flag
  'The route changed after this description was written.': 'La ruta cambió después de escribir esta descripción.',
  'Rewrite with Copilot': 'Reescribir con Copilot',
  'Edit': 'Editar',
  'Still accurate': 'Sigue siendo correcta',
  'Edit description': 'Editar descripción',
  'Write a description': 'Escribir una descripción',
  'No description for this day yet.': 'Este día aún no tiene descripción.',
  'What this day is, and what it costs.': 'Qué es este día y qué cuesta.',
  'Stops now': 'Paradas actuales',
  'ride hrs': 'h de ruta',
  'Rewrite this day\'s description to match the route it actually has now — set_day_field summary, and the title too if the endpoints no longer match. One or two honest sentences in the field-guide voice, trade-offs included. Do not change the route.':
    'Reescribe la descripción de este día para que coincida con la ruta que tiene ahora — set_day_field summary, y también el título si los extremos ya no coinciden. Una o dos frases honestas con la voz de la guía de campo, incluyendo las concesiones. No cambies la ruta.',
  'Remove meal': 'Quitar comida',
  'Why:': 'Por qué:',
  'Trade-off:': 'Costo:',
  'Logistics:': 'Logística:',
  'Best light': 'Luz',
  'Parking': 'Estacionamiento',
  '★ Anchor day — trim elsewhere first': '★ Día ancla — recortar primero en otro lado',
  'Outbound': 'Ida',
  'Rally': 'Rally',
  'Destination': 'Destino',
  'More': 'Más',
  'More phases': 'Más fases',
  'no days': 'sin días',
  'phase names · pace · absolute range · MPG · dusk · calendar UTC offset': 'nombres de fase · ritmo · autonomía absoluta · MPG · anochecer · desfase UTC del calendario',
  'Return': 'Regreso',
  'Satellite': 'Satélite',
  'Streets': 'Calles',
  'Road': 'Ruta',
  'Photo': 'Foto',
  // weather
  'checking forecast…': 'consultando el pronóstico…',
  'Forecast not in range yet — Open-Meteo covers ~16 days out. Check back closer to the date.': 'El pronóstico aún no alcanza — Open-Meteo cubre ~16 días hacia adelante. Revisa más cerca de la fecha.',
  'near': 'cerca de',
  'wind': 'viento',
  'Clear': 'Despejado',
  'Mostly clear': 'Mayormente despejado',
  'Partly cloudy': 'Parcialmente nublado',
  'Overcast': 'Cubierto',
  'Fog': 'Niebla',
  'Rime fog': 'Niebla escarchada',
  'Light drizzle': 'Llovizna suave',
  'Drizzle': 'Llovizna',
  'Heavy drizzle': 'Llovizna intensa',
  'Light rain': 'Lluvia suave',
  'Rain': 'Lluvia',
  'Heavy rain': 'Lluvia intensa',
  'Freezing rain': 'Lluvia helada',
  'Light snow': 'Nieve suave',
  'Snow': 'Nieve',
  'Heavy snow': 'Nieve intensa',
  'Snow grains': 'Granos de nieve',
  'Rain showers': 'Chubascos',
  'Violent showers': 'Chubascos violentos',
  'Snow showers': 'Chubascos de nieve',
  'Thunderstorms': 'Tormentas eléctricas',
  'T-storms w/ hail': 'Tormentas con granizo',
  'Changing the start date re-pins every day to the new calendar. Fuel warnings and feasibility use the bike range set here.': 'Cambiar la fecha de inicio vuelve a fijar cada día al nuevo calendario. Las advertencias de bencina y la factibilidad usan el rango de moto configurado aquí.',
  // detail modal
  'Arrive': 'Llegada',
  'On the ground': 'En tierra',
  'Roll out': 'Salida',
  'Leg in': 'Tramo de llegada',
  'Time here (min)': 'Tiempo aquí (min)',
  'Fuel stop': 'Parada de bencina',
  'Move to day': 'Mover al día',
  'Remove stop': 'Eliminar parada',
  'Done': 'Listo',
  'Distance': 'Distancia',
  'Ride time': 'Tiempo de ruta',
  'stop': 'parada',
  'leg': 'tramo',
  'Depart (short)': 'Salida',
  'This stop no longer exists.': 'Esta parada ya no existe.',
  'This leg no longer exists.': 'Este tramo ya no existe.',
  'searching…': 'buscando…',
  'Choose…': 'Elegir…',
  'Type any real place — e.g. Bozeman, MT': 'Escribe cualquier lugar real — p. ej. Bozeman, MT',
  'Start:': 'Inicio:',
  'End:': 'Fin:',
  '✓ Location updated →': '✓ Ubicación actualizada →',
  '— route re-snaps on save': '— la ruta se recalcula al guardar',
  'Rule of thumb extras: cash in small bills for vendor-heavy events, and the $80 America the Beautiful pass if the route touches multiple national parks — it usually pays for itself twice.': 'Extras de regla general: efectivo en billetes chicos para eventos con muchos vendedores, y el pase America the Beautiful de $80 si la ruta toca varios parques nacionales — normalmente se paga solo dos veces.',
  'analyzing the route…': 'analizando la ruta…',
  'working through the trip…': 'trabajando el viaje…',
  'drafting changes…': 'redactando cambios…',
  'characters': 'caracteres',
  // chat greeting + suggestion chips (clicking sends the Spanish text, so the
  // optimizer is asked in Spanish and answers in Spanish)
  "I hold the whole plan — every waypoint, booking, fuel stop, and constraint — plus the live metrics from your edits. Ask for analysis, or tell me to rework the trip and I'll propose concrete changes you can preview and apply.": 'Tengo el plan completo — cada parada, reserva, carga de bencina y restricción — más las métricas en vivo de tus ediciones. Pídeme análisis, o dime que rearme el viaje y te propondré cambios concretos que puedes previsualizar y aplicar.',
  'Run a full feasibility read — where does this plan break?': 'Haz una lectura completa de factibilidad — ¿dónde se rompe este plan?',
  'Where should we break up the loops and the long days?': '¿Dónde deberíamos cortar los circuitos y los días largos?',
  'Rebuild the trip to fix every failed gate and save it as "Fixed gates"': 'Rearma el viaje para corregir cada corte incumplido y guárdalo como "Cortes corregidos"',
  'Give me a lower-mileage version of the whole trip, save as "Relaxed"': 'Dame una versión del viaje completo con menos kilometraje, guárdala como "Relajado"',
  // map hints
  'Editing': 'Editando',
  '— click map to add a stop · drag markers · click stops & legs for details': '— clic en el mapa para agregar una parada · arrastra los marcadores · clic en paradas y tramos para detalles',
  '— drag the route to reshape it · click the map to add a stop · drag markers': '— arrastra la ruta para remodelarla · clic en el mapa para agregar una parada · arrastra los marcadores',
  '— tap the map to add a stop · drag markers · tap stops & legs for details': '— toca el mapa para agregar una parada · arrastra los marcadores · toca paradas y tramos para ver detalles',
  'Whole-trip view': 'Vista del viaje completo',
  '— hover a route for leg info, click for details, pick a day to edit': '— pasa el cursor por una ruta para info del tramo, clic para detalles, elige un día para editar',
  // packing edit
  'Add an item…': 'Agregar un ítem…',
  'Add': 'Agregar',
  'Restore removed items': 'Restaurar ítems eliminados',
  // dashboard
  'Switch trip': 'Cambiar de viaje',
  'in the library': 'en la biblioteca',
  'saved': 'guardados',
  'Save this plan as a named permutation': 'Guardar este plan como una permutación con nombre',
  'Change which trip you are planning': 'Cambiar qué viaje estás planificando',
  'Dashboard': 'Panel',
  'Planner': 'Planificador',
  'Plan the trip': 'Planificar el viaje',
  'Get ready': 'Prepararse',
  'Trip file': 'Archivo del viaje',
  'Day by day, stops, food, lodging': 'Día a día, paradas, comida, alojamiento',
  'days need attention': 'días requieren atención',
  'No hard failures': 'Sin fallas graves',
  'Fuel, lodging, food, tickets': 'Bencina, alojamiento, comida, entradas',
  'AI': 'IA',
  'Ask for changes, preview, apply': 'Pide cambios, previsualiza, aplica',
  'Per rider, saved on this device': 'Por motociclista, guardado en este dispositivo',
  'All booked': 'Todo reservado',
  'Bookings still to make': 'Reservas pendientes',
  'GPS': 'GPS',
  'Turn-by-turn, ahead or behind plan': 'Indicaciones giro a giro, adelantados o atrasados',
  'Language, theme, units': 'Idioma, tema, unidades',
  'Save this trip as JSON': 'Guardar este viaje como JSON',
  'Load a trip from JSON': 'Cargar un viaje desde JSON',
  'From scratch, a description, or the template': 'Desde cero, una descripción o la plantilla',
  'Back to the bundled template': 'Volver a la plantilla incluida',
  // highway shields
  'Highway shields': 'Escudos de carretera',
  'Developer tools': 'Herramientas de desarrollo',
  'Build': 'Versión',
  'Route shields under each stop. Experimental — remove it if it reads as clutter.': 'Escudos de ruta bajo cada parada. Experimental — quítalo si se ve desordenado.',
  'On': 'Sí',
  'Off': 'No',
  'National park': 'Parque nacional',
  // module editor
  'add an option': 'agregar una opción',
  'move to': 'mover a',
  'another day…': 'otro día…',
  'Name': 'Nombre',
  'Timing': 'Horario',
  'Why': 'Por qué',
  'Trade-off': 'Costo',
  'Logistics': 'Logística',
  'Next': 'Siguiente',
  'ETA': 'ETA',
  'left': 'restante',
  'ON PLAN': 'SEGÚN EL PLAN',
  'LATE': 'TARDE',
  'ahead': 'adelante',
  'away': 'de distancia',
  'Speed limit': 'Límite de velocidad',
  'EARLY': 'TEMPRANO',
  'LOCATING…': 'UBICANDO…',
  'WAITING FOR GPS': 'ESPERANDO GPS',
  // ride mode hub
  'Ride menu': 'Menú de ruta',
  'Leg': 'Tramo',
  'Voice': 'Voz',
  'Map settings': 'Ajustes del mapa',
  'Credits': 'Créditos',
  'Your name, so the others know who is who.': 'Tu nombre, para que los demás sepan quién es quién.',
  'Keep this code. It is how you get back in on a new phone.': 'Guarda este código. Así vuelves a entrar desde otro teléfono.',
  'Leave this trip': 'Salir de este viaje',
  'Save': 'Guardar',
  'Joining a trip? Enter your name and the code the organiser sent.': '¿Te unes a un viaje? Escribe tu nombre y el código que te enviaron.',
  'Your name': 'Tu nombre',
  'Join trip': 'Unirse al viaje',
  'or': 'o',
  'Organizing the trip? Sign in by email so it is recoverable on a new phone.': '¿Organizas el viaje? Inicia sesión por correo para poder recuperarlo en otro teléfono.',
  'Rider': 'Motociclista',
  'No GPS available in this browser.': 'No hay GPS disponible en este navegador.',
  'Location needs a secure connection — open the app over https. A plain http address will not get a fix on a phone.': 'La ubicación necesita una conexión segura — abre la app por https. Una dirección http simple no obtiene señal en el teléfono.',
  'Waiting for a GPS fix. Outdoors with a clear view of the sky is fastest.': 'Esperando señal GPS. Al aire libre con vista despejada del cielo es más rápido.',
  'Location permission denied — allow it in your browser settings to ride with the HUD.': 'Permiso de ubicación denegado — actívalo en los ajustes del navegador para usar el HUD.',
  'Share': 'Compartir',
  'Sign in to share this trip with your riders. Every change syncs to everyone.': 'Inicia sesión para compartir este viaje con tus motociclistas. Cada cambio se sincroniza con todos.',
  'you@example.com': 'tu@ejemplo.com',
  'Send link': 'Enviar enlace',
  'Check your email for the sign-in link.': 'Revisa tu correo para el enlace de acceso.',
  'Riders join with this code. Everything they change appears here.': 'Los motociclistas se unen con este código. Todo lo que cambien aparece aquí.',
  'Share this trip': 'Compartir este viaje',
  'Shared. Send the code to your riders.': 'Compartido. Envía el código a tus motociclistas.',
  'Join code': 'Código',
  'Join': 'Unirse',
  'Joined.': 'Te uniste.',
  'Live': 'En vivo',
  'Syncing': 'Sincronizando',
  'Waiting for signal': 'Esperando señal',
  'Offline': 'Sin conexión',
  'Sign out': 'Cerrar sesión',
  'Sharing is not configured on this build.': 'Compartir no está configurado en esta versión.',
  'Basemap': 'Mapa base',
  'Density': 'Densidad',
  'Minimalist': 'Minimalista',
  'Detailed': 'Detallado',
  'then': 'luego',
  'Route overview': 'Vista de la ruta',
  'Re-center': 'Recentrar',
  'End navigation': 'Terminar navegación',
  // ride mode
  'Exit': 'Salir',
  'Overview': 'Vista general',
  'Mute': 'Silenciar',
  'Unmute': 'Sonido',
  'Recenter': 'Recentrar',
  'ahead of plan': 'adelantados al plan',
  'behind plan': 'atrasados del plan',
  'on plan': 'según el plan',
  // reimagined shell: Home / PLAN·PREP·RIDE / Copilot dock
  'The AI roadbook for motorcycle trips': 'El roadbook con IA para viajes en moto',
  'Where do you want to ride?': '¿Adónde quieres rodar?',
  'Describe riders, days, region, pace — the AI drafts a routed, dated, feasibility-graded plan you can negotiate with.': 'Describe motociclistas, días, región, ritmo — la IA redacta un plan ruteado, fechado y calificado por factibilidad que puedes negociar.',
  'Describe riders, days, region, and pace. Roadbook researches real opportunities, compares routed choices, and lets you shape every piece before the trip is created.': 'Describe motociclistas, días, región y ritmo. Roadbook investiga oportunidades reales, compara opciones ruteadas y te deja ajustar cada parte antes de crear el viaje.',
  'e.g. 4 riders, 6 days, Denver loop through the San Juans — Million Dollar Highway, hot springs one night, big scenic passes, moderate daily miles.': 'ej. 4 motociclistas, 6 días, circuito desde Denver por los San Juans — Million Dollar Highway, termas una noche, grandes pasos escénicos, millas diarias moderadas.',
  'Build with AI': 'Construir con IA',
  'Plan with AI': 'Planear con IA',
  'Blank trip': 'Viaje en blanco',
  'Sturgis template': 'Plantilla Sturgis',
  'Import JSON': 'Importar JSON',
  'Your trips': 'Tus viajes',
  'Continue planning →': 'Seguir planificando →',
  'Open →': 'Abrir →',
  'Delete': 'Eliminar',
  'Delete this trip': 'Eliminar este viaje',
  'Delete this trip?': '¿Eliminar este viaje?',
  'its days, scenarios, and chat go with it. There is no undo for this.': 'sus días, escenarios y chat se van con él. Esto no se puede deshacer.',
  'Plan': 'Planificar',
  'Prep': 'Preparar',
  'Prep board': 'Tablero de preparación',
  'Ridden': 'Rodado',
  'Day': 'Día',
  'of': 'de',
  'the plan holds': 'el plan aguanta',
  'No gate, fuel, or daylight issues anywhere in the plan.': 'Sin problemas de horarios, bencina ni luz de día en todo el plan.',
  'Full feasibility study': 'Estudio de factibilidad completo',
  'Ask the AI to fix it': 'Pídele a la IA que lo arregle',
  'Fix every failing day in this plan — retime departures, move stops to neighboring days, or trim — keep the anchor days intact, and save the result as a scenario.': 'Arregla cada día que falla en este plan — reprograma salidas, mueve paradas a días vecinos o recorta — mantén intactos los días ancla y guarda el resultado como escenario.',
  'Status': 'Estado',
  'Bookings': 'Reservas',
  'Budget & fuel': 'Presupuesto y bencina',
  'Fuel from routed miles · everything else adjustable': 'Bencina según millas ruteadas · todo lo demás ajustable',
  'Export, import, GPX, calendar, reset': 'Exportar, importar, GPX, calendario, restablecer',
  'Every day, one file, ETAs on the waypoints': 'Cada día, un archivo, ETAs en los puntos',
  'Departures, gates, dinners on every phone': 'Salidas, horarios y cenas en cada teléfono',
  'Nothing to reserve — this trip has no booking checklist yet.': 'Nada que reservar — este viaje aún no tiene lista de reservas.',
  'Copilot': 'Copiloto',
  'Sure?': '¿Seguro?',
  'Save scenario': 'Guardar escenario',
  'Name this trip permutation': 'Nombra esta permutación del viaje',
  'e.g. Relaxed — lower miles': 'ej. Relajado — menos millas',
  'Reset this trip?': '¿Restablecer este viaje?',
  // design pass: silhouettes, start-from gallery, copilot chips
  'Start from': 'Partir desde',
  'the full field guide': 'la guía de campo completa',
  'Copy it →': 'Copiarla →',
  'An empty frame — add days and stops by hand': 'Un marco vacío — agrega días y paradas a mano',
  'Start empty →': 'Partir vacío →',
  'A trip file from a riding buddy': 'Un archivo de viaje de un compañero de ruta',
  'Load it →': 'Cargarlo →',
  '⌘↵ builds it · ': '⌘↵ lo construye · ',
  'every draft is editable, gradeable, undoable': 'cada borrador es editable, calificable, reversible',
  '⌘↵ opens the planner · ': '⌘↵ abre el planificador · ',
  'compare first, create when it feels right': 'compara primero, crea cuando se sienta bien',
  'Ask Copilot': 'Pregúntale al Copiloto',
  'Find route opportunities': 'Buscar oportunidades de ruta',
  'Research this day as route-and-stop opportunities. Use verified places and Valhalla to compare 2–3 bundles of roads, fuel, food, lodging, and attractions. Show the measured time, distance, fuel-gap, and group trade-offs. Do not change the trip yet — let me choose or combine pieces first.': 'Investiga este día como oportunidades de ruta y paradas. Usa lugares verificados y Valhalla para comparar 2–3 combinaciones de carreteras, combustible, comida, alojamiento y atracciones. Muestra tiempo, distancia, tramo sin combustible y compromisos del grupo medidos. No cambies el viaje todavía: déjame elegir o combinar partes primero.',
  'Review this day in detail — where is it tight, what breaks, and what would you change?': 'Revisa este día en detalle — dónde va justo, qué falla y qué cambiarías.',
  'Routing': 'Ruteando',
  'rider': 'motociclista',
  // collaborate mode
  'Crew': 'Grupo',
  'Ride together': 'Rodar juntos',
  'Share this trip with the crew. Riders join from a link, make edits that arrive as proposals, drop recommendations, and vote when the plan is ready. You stay road captain — the plan publishes when you say it does.': 'Comparte este viaje con el grupo. Los motociclistas entran por un enlace, sus ediciones llegan como propuestas, dejan recomendaciones y votan cuando el plan está listo. Tú sigues siendo el capitán de ruta — el plan se publica cuando tú lo digas.',
  'Your name — shown to the crew': 'Tu nombre — visible para el grupo',
  'Start sharing': 'Empezar a compartir',
  'Starting…': 'Iniciando…',
  'Reaching the crew…': 'Contactando al grupo…',
  'Invite riders — plan it together': 'Invita motociclistas — planifíquenlo juntos',
  'Proposals, votes, recommendations': 'Propuestas, votos, recomendaciones',
  'shared': 'compartido',
  'joined': 'en el grupo',
  'DRAFT': 'BORRADOR',
  'VOTING': 'VOTACIÓN',
  'PUBLISHED': 'PUBLICADO',
  'Planning is open — edit, propose, recommend.': 'La planificación está abierta — edita, propone, recomienda.',
  'The captain called the vote. Say whether you\'re in.': 'El capitán llamó a votar. Di si te sumas.',
  'The plan is published. Prep continues; the route is locked.': 'El plan está publicado. La preparación sigue; la ruta queda fija.',
  'Call the vote': 'Llamar a votar',
  'Publish the plan': 'Publicar el plan',
  'Back to planning': 'Volver a planificar',
  'Reopen planning': 'Reabrir la planificación',
  'Copy invite': 'Copiar invitación',
  'Copied ✓': 'Copiado ✓',
  'Your changes': 'Tus cambios',
  'Send to the captain': 'Enviar al capitán',
  'Discard & resync': 'Descartar y resincronizar',
  'Your vote': 'Tu voto',
  'I\'m in': 'Me sumo',
  'I have concerns': 'Tengo dudas',
  'What worries you — day, distance, budget…': 'Qué te preocupa — día, distancia, presupuesto…',
  'Riders': 'Motociclistas',
  'you': 'tú',
  'in': 'se suma',
  'concerns': 'dudas',
  'no note': 'sin nota',
  'Remove from crew': 'Quitar del grupo',
  'Proposals': 'Propuestas',
  'None yet. Rider edits arrive here for the captain\'s call.': 'Aún no hay. Las ediciones de los motociclistas llegan aquí para la decisión del capitán.',
  'Decline': 'Rechazar',
  'applied': 'aplicada',
  'declined': 'rechazada',
  'Recommendations': 'Recomendaciones',
  'Nothing yet — routes, roadhouses, must-sees.': 'Nada aún — rutas, paradores, imperdibles.',
  'Recommend a road, a stop, a change…': 'Recomienda una ruta, una parada, un cambio…',
  'Show this leg on the map': 'Ver este tramo en el mapa',
  'Hide the panel': 'Ocultar el panel',
  'Show the panel': 'Mostrar el panel',
  'Back to the map': 'Volver al mapa',
  'Published plan': 'Plan publicado',
  'reopen planning from the Crew board to edit': 'reabre la planificación desde el tablero del Grupo para editar',
  'your edits arrive as proposals to the captain': 'tus ediciones llegan como propuestas al capitán',
  'Join this ride?': '¿Unirte a esta ruta?',
  'Join the crew': 'Unirme al grupo',
  'Joining…': 'Uniéndome…',
  'e.g. Marco': 'ej. Marco',
  // ride mode rebuilt
  'North up': 'Norte arriba',
  'Track up': 'Rumbo arriba',
  'Arrived': 'Llegaste',
  'End ride': 'Terminar ruta',
  'Stops ahead': 'Paradas por delante',
  'margin': 'de margen',
  'ridden today': 'recorridas hoy',
  // input audit: gates, bookings, dusk/tz, phase & anchor controls
  'Hard gates': 'Horarios límite',
  'be there by — feasibility grades against these': 'llegar antes de — la factibilidad se califica contra esto',
  'What has to happen': 'Qué tiene que pasar',
  'at which stop…': 'en cuál parada…',
  'Add gate': 'Agregar horario límite',
  'New gate': 'Nuevo horario límite',
  'Remove this gate': 'Quitar este horario límite',
  'Anchor': 'Ancla',
  'Anchor days are protected — the AI trims elsewhere first': 'Los días ancla están protegidos — la IA recorta primero en otro lado',
  'Sure? Later days shift earlier': '¿Seguro? Los días siguientes se adelantan',
  'Add booking': 'Agregar reserva',
  'Remove this booking': 'Quitar esta reserva',
  'Nothing on the checklist yet — add the calls this trip depends on.': 'Aún no hay nada en la lista — agrega las llamadas de las que depende este viaje.',
  'What to book — hotel, table, tickets': 'Qué reservar — hotel, mesa, entradas',
  'For when — “Night of Fri Aug 14”': 'Para cuándo — “Noche del vie 14 ago”',
  'Where / phone': 'Dónde / teléfono',
  'Notes — backups, what to ask for': 'Notas — respaldos, qué pedir',
  'Dusk (after-dark warnings)': 'Anochecer (avisos de oscuridad)',
  'UTC offset (calendar export)': 'Desfase UTC (exportar calendario)',
  'Dusk drives the after-dark warnings; the UTC offset places .ics calendar times in the trip’s zone.': 'El anochecer maneja los avisos de oscuridad; el desfase UTC ubica las horas del calendario .ics en la zona del viaje.',
  'Bike — type anything': 'Moto — escribe lo que sea',
  'Tickets, entries & passes': 'Entradas, accesos y pases',
  'Method: departure times from each day\'s plan, routed leg durations (OSRM, speed-calibrated for real highway pace, scaled by the trip\'s group-pace setting), planned time-on-ground at every stop, checked against the trip\'s hard gates, its configured fuel range, its dusk setting, and booking status. Saved-plan rows use cached routing where available and planned mileage otherwise.': 'Método: horas de salida del plan de cada día, duraciones de tramo ruteadas (OSRM, calibradas a la velocidad real de carretera y escaladas por el ritmo de grupo del viaje), tiempo en tierra planificado en cada parada, verificado contra los horarios límite del viaje, su autonomía de bencina configurada, su hora de anochecer y el estado de reservas. Las filas de planes guardados usan ruteo en caché cuando existe y millaje planificado si no.',
  'Back to the bundled Sturgis template. Every edit to this trip is discarded.': 'Vuelve a la plantilla Sturgis incluida. Se descarta cada edición de este viaje.',
  // pace + off-road pin (planning)
  'Group pace buffer %': 'Margen de ritmo de grupo %',
  'The pace buffer slows every planned leg for group riding — set 0 for a solo trip, 15+ for a big group.': 'El margen de ritmo ralentiza cada tramo planificado para rodar en grupo — usa 0 para un viaje solo, 15+ para un grupo grande.',
  'This pin sits off the road network, so routing detours to reach it. Drag it onto the road or re-pick the stop via search.': 'Este pin está fuera de la red de caminos, así que el ruteo se desvía para tocarlo. Arrástralo al camino o vuelve a elegir la parada con el buscador.',
  'off road': 'fuera del camino',
  // place verification — AI-authored stops checked against the places database
  'unverified': 'sin verificar',
  'The places database found no real business at this pin, so this stop is unconfirmed. Re-pick it with search before you ride.': 'La base de datos de lugares no encontró ningún negocio real en este pin, así que la parada no está confirmada. Vuelve a elegirla con el buscador antes de rodar.',
  'Checked against the live places database — this is a real business at these coordinates.': 'Verificado contra la base de datos de lugares — es un negocio real en estas coordenadas.',
  // plans strip: saved-plan switching on the PLAN surface
  'Plans': 'Planes',
  'Current': 'Actual',
  'Save plan as…': 'Guardar plan como…',
  'Apply as new trip': 'Aplicar como viaje nuevo',
  'Apply for the group': 'Aplicar para el grupo',
  'Name this version — e.g. Solo Thursday': 'Nombra esta versión — p. ej. Jueves solo',
  'Snapshots the whole current plan under a name. Copilot restructures land here automatically too.': 'Guarda una copia del plan actual bajo un nombre. Las reestructuraciones del Copiloto también llegan aquí automáticamente.',
  'Update': 'Actualizar',
  'The working plan has drifted from this saved plan — Update writes your edits back into it.': 'El plan de trabajo se apartó de este plan guardado — Actualizar escribe tus ediciones de vuelta en él.',
  'You are on this plan, with unsaved edits — Update writes them back into it.': 'Estás en este plan, con ediciones sin guardar — Actualizar las escribe de vuelta en él.',
  'This is the current plan.': 'Este es el plan actual.',
  'The working plan — unsaved. Tap to name it.': 'El plan de trabajo — sin guardar. Toca para nombrarlo.',
  'Compare and load saved plans — save new ones from the Plans strip': 'Compara y carga planes guardados — guarda nuevos desde la franja Planes',
  'Saved plans': 'Planes guardados',
  'None yet. Save one from the Plans strip at the top of the trip overview — or ask Copilot to restructure the trip and save the result — then compare plans here and swap between them.': 'Aún no hay. Guarda uno desde la franja Planes arriba del resumen del viaje — o pide al Copiloto que reestructure el viaje y guarde el resultado — y luego compara planes aquí y cambia entre ellos.',
  'Load for the group': 'Cargar para el grupo',
  'Just me — new trip': 'Solo yo — viaje nuevo',
  'Personal copy': 'Copia personal',
  'Duplicate trip': 'Duplicar viaje',
  'Create my copy': 'Crear mi copia',
  'A separate copy of the current plan as its own trip on this phone — unshared, so nothing you change there reaches the group.': 'Una copia aparte del plan actual como su propio viaje en este teléfono — sin compartir, así que nada de lo que cambies ahí llega al grupo.',
  'A separate copy of this trip to experiment on — the original stays as it is.': 'Una copia aparte de este viaje para experimentar — el original queda como está.',
  'Group: every rider’s plan switches to this — it syncs like any other edit. Just me: a separate trip only on this phone; the group plan stays untouched.': 'Grupo: el plan de cada piloto cambia a este — se sincroniza como cualquier otra edición. Solo yo: un viaje aparte solo en este teléfono; el plan del grupo queda intacto.',
  'Group: these changes sync to every rider. Just me: they land in a separate trip on this phone.': 'Grupo: estos cambios se sincronizan a todos los pilotos. Solo yo: quedan en un viaje aparte en este teléfono.',
  'The current plan is auto-saved first — switching back is always possible.': 'El plan actual se guarda automáticamente primero — siempre puedes volver.',
  // ride mode: destination control + speed limit + mid-ride search
  'Add a stop ahead': 'Agregar una parada adelante',
  'Gas, food, a place…': 'Bencina, comida, un lugar…',
  'Searching…': 'Buscando…',
  'No matches — try adding the town name.': 'Sin resultados — agrega el nombre del pueblo.',
  'Stop': 'Parada',
  'FUEL': 'BENCINA',
  'Go next': 'Ir ahora',
  'Skip': 'Omitir',
  'Skipped': 'Omitida',
  'skipped': 'omitida',
  'Restore': 'Restaurar',
  'UNDO': 'DESHACER',
  'SPEED': 'SPEED',
  'LIMIT': 'LIMIT',

  // landing page / accounts
  'Plan the ride.': 'Planifica la ruta.',
  'Then ride the plan.': 'Después ródala.',

  // landing page — the front door (Sep 13, 2026)
  'No account needed to start. Everything works offline on this device; create an account later and your trips come with you.':
    'No hace falta cuenta para empezar. Todo funciona sin conexión en este dispositivo; crea una cuenta más tarde y tus viajes se van contigo.',
  'What Roadbook does': 'Qué hace Roadbook',
  'How it works': 'Cómo funciona',
  'A sentence in. A ride you can trust out.': 'Entra una frase. Sale una ruta de fiar.',
  'Say where, how long, and how you like to ride.': 'Di adónde, cuánto tiempo y cómo te gusta rodar.',
  'The builder searches real places, measures every option on the road, and shows the trade-offs — miles, riding time, fuel gaps, the climb — before anything is created. You pick the route; only then does the trip exist.':
    'El constructor busca lugares reales, mide cada opción sobre la carretera y te enseña las diferencias — millas, tiempo en moto, huecos de combustible, el desnivel — antes de crear nada. Tú eliges la ruta; solo entonces existe el viaje.',
  'See what would go wrong. Fix it in one tap.': 'Ve qué fallaría. Arréglalo con un toque.',
  'Days carry a grade and say exactly what is wrong: a 214-mile gap on a 180-mile tank, a check-in you would miss by twelve minutes. Every change — yours or the Copilot’s — is an edit you can see, apply, and undo.':
    'Cada día lleva una nota y dice exactamente qué falla: un hueco de 214 millas con un depósito de 180, un check-in al que llegarías doce minutos tarde. Cada cambio — tuyo o del Copiloto — es una edición que puedes ver, aplicar y deshacer.',
  'Ride it from the handlebars.': 'Ródalo desde el manillar.',
  'Ride Mode is full navigation: course-up chase camera, spoken turns, posted speed limits, live traffic on the motorcycle route, and how far ahead or behind the plan you are running. Skip a stop, add a fuel stop ahead by voice, and the plan follows.':
    'El Modo Ruta es navegación completa: cámara orientada al rumbo, giros hablados, límites de velocidad señalizados, tráfico en vivo sobre la ruta de moto y cuánto vas por delante o por detrás del plan. Salta una parada, añade gasolina más adelante con la voz, y el plan te sigue.',
  'You': 'Tú',
  'Thursday · grade C': 'Jueves · nota C',
  'between fuel stops · your range is': 'entre gasolineras · tu autonomía es',
  'Copilot proposes': 'El Copiloto propone',
  'Add fuel': 'Añadir gasolina',
  'Move lunch': 'Mover el almuerzo',
  'Thursday → A': 'Jueves → A',
  'Built for the bike': 'Hecho para la moto',
  'The things a map app cannot know.': 'Lo que una app de mapas no puede saber.',
  'Fuel against your real range': 'Combustible frente a tu autonomía real',
  'Every leg is checked against the range you set for your bike, not a default. A gap it cannot cover is red before you leave.':
    'Cada tramo se comprueba contra la autonomía que fijaste para tu moto, no un valor por defecto. Un hueco que no cubre está en rojo antes de salir.',
  'Ferry departures, hotel check-ins, dinner reservations. Timed commitments become constraints the grade respects and the ride announces.':
    'Salidas de ferry, check-ins de hotel, reservas de cena. Los compromisos con hora se vuelven restricciones que la nota respeta y la ruta anuncia.',
  'Real places, verified': 'Lugares reales, verificados',
  'Every stop is a live listing with hours and a phone number, or a pin you placed on purpose. The AI never invents a gas station.':
    'Cada parada es una ficha real con horario y teléfono, o un pin que colocaste a propósito. La IA nunca se inventa una gasolinera.',
  'Crew by code': 'Grupo por código',
  'Share one code. Everyone rides the same roadbook, edits arrive as proposals, and the road captain has the final call.':
    'Comparte un código. Todos ruedan con el mismo roadbook, las ediciones llegan como propuestas y el capitán tiene la última palabra.',
  'Offline first': 'Sin conexión, primero',
  'The roadbook lives on your phone. No bars in the canyon, no problem — and an account backs it up when you have signal.':
    'El roadbook vive en tu móvil. Sin cobertura en el cañón, sin problema — y una cuenta lo respalda cuando tengas señal.',
  'GPX with your ETAs': 'GPX con tus horas de llegada',
  'Export the plan to any GPS with the planned arrival time on every waypoint, and the calendar file for the crew.':
    'Exporta el plan a cualquier GPS con la hora de llegada prevista en cada punto, y el archivo de calendario para el grupo.',
  'Start from a template': 'Empieza desde una plantilla',
  'Or hand a proven route to the AI.': 'O entrégale a la IA una ruta probada.',
  'stops': 'paradas',
  'Your roadbook, on every phone': 'Tu roadbook, en cualquier móvil',
  'Give the plan a second home.': 'Dale al plan un segundo hogar.',
  'Your trips live on this device first. An account backs the whole library up — delete the app, change phones, or lose the bike bag, and it is still there when you sign in.':
    'Tus viajes viven primero en este dispositivo. Una cuenta respalda toda la biblioteca — borra la app, cambia de móvil o pierde la alforja, y sigue ahí cuando inicies sesión.',
  'Sign in on a new phone and your trips come down.': 'Inicia sesión en un móvil nuevo y tus viajes bajan solos.',
  'Saved places, your bike and its range, your riding style.': 'Lugares guardados, tu moto y su autonomía, tu estilo de rodar.',
  'Crews still join with a code — no email needed in the car park.': 'Los grupos siguen uniéndose con un código — sin correo en el aparcamiento.',
  'Real roads, real places, and a roadbook that stays on your phone until you decide it needs an account.':
    'Carreteras reales, lugares reales y un roadbook que se queda en tu móvil hasta que decidas que necesita una cuenta.',
  'Landing': 'Portada',

  // landing page — AI-first (Sep 13, 2026)
  'Tell it the ride.': 'Cuéntale la ruta.',
  'It builds the roadbook.': 'Él construye el roadbook.',
  'Not a chatbot bolted onto a map. Roadbook’s planner searches real places live, routes every option on real roads for a motorcycle, checks fuel, daylight and your check-ins, and shows you the trade-offs before a single stop is committed. Then it rides with you.':
    'No es un chatbot pegado a un mapa. El planificador de Roadbook busca lugares reales en vivo, traza cada opción por carreteras reales para moto, comprueba combustible, luz y tus check-ins, y te enseña las diferencias antes de comprometer una sola parada. Después rueda contigo.',
  'Searches real places, live': 'Busca lugares reales, en vivo',
  'Measures every option on motorcycle roads': 'Mide cada opción por carreteras de moto',
  'Grades every day before you commit': 'Califica cada día antes de que te comprometas',
  'Rides with you, turn by turn': 'Rueda contigo, giro a giro',
  'What the planner does': 'Qué hace el planificador',
  'It does the research a good road captain would.': 'Hace la investigación que haría un buen capitán de ruta.',
  'Fuel, food, beds and sights come from live listings with hours, ratings and phone numbers. A stop it cannot verify is flagged for you to re-pick — never invented.':
    'Gasolina, comida, camas y lugares salen de fichas en vivo con horarios, valoraciones y teléfono. Una parada que no puede verificar se marca para que la vuelvas a elegir — nunca se inventa.',
  'The Pollard · verified · 4.6 ★ · open until 10 PM': 'The Pollard · verificado · 4.6 ★ · abierto hasta las 10 PM',
  'Measures every option on the road': 'Mide cada opción sobre la carretera',
  'Up to three routes at a time, on motorcycle roads at your group’s pace: miles, riding time, the longest day, the biggest fuel gap against your range, the climb, and what each detour costs.':
    'Hasta tres rutas a la vez, por carreteras de moto al ritmo de tu grupo: millas, tiempo en moto, el día más largo, el mayor hueco de combustible frente a tu autonomía, el desnivel y lo que cuesta cada desvío.',
  'Shows the trade-offs, then waits': 'Enseña las diferencias, y espera',
  'Why a route works, how it fits your group, what it costs you. Change one stop, keep the roads and change the stops, keep the stops and change the roads, or shorten it. Nothing is created until you say so.':
    'Por qué funciona una ruta, cómo encaja con tu grupo, qué te cuesta. Cambia una parada, mantén las carreteras y cambia las paradas, mantén las paradas y cambia las carreteras, o acórtala. No se crea nada hasta que tú lo digas.',
  'Keeps working after the trip exists': 'Sigue trabajando cuando el viaje ya existe',
  'The Copilot proposes edits you can see, apply and undo. Ask it to re-plan the roads and it locks your booked beds and timed commitments first. It learns which places you pick — privately.':
    'El Copiloto propone ediciones que puedes ver, aplicar y deshacer. Pídele replantear las carreteras y primero bloquea tus camas reservadas y compromisos con hora. Aprende qué lugares eliges — en privado.',
  'Add fuel · Sinclair, Ten Sleep': 'Añadir gasolina · Sinclair, Ten Sleep',
  'Why it is different': 'Por qué es distinto',
  'Other planners draw a line. Roadbook builds a plan.': 'Otros planificadores dibujan una línea. Roadbook construye un plan.',
  'A chatbot on a map': 'Un chatbot sobre un mapa',
  'Names a gas station from memory.': 'Nombra una gasolinera de memoria.',
  'Looks it up, checks it is open, and snaps the stop to it.': 'La busca, comprueba que está abierta y ancla la parada a ella.',
  'Draws one line and calls it a route.': 'Dibuja una línea y la llama ruta.',
  'Measures three on motorcycle roads and grades every day.': 'Mide tres por carreteras de moto y califica cada día.',
  'Rewrites your trip when you ask for a change.': 'Reescribe tu viaje cuando pides un cambio.',
  'Proposes an edit you can see, apply and undo.': 'Propone una edición que puedes ver, aplicar y deshacer.',
  'Stops helping once the plan is made.': 'Deja de ayudar cuando el plan está hecho.',
  'Rides with you: turn by turn, fuel range, gate margins, live traffic on the motorcycle route.': 'Rueda contigo: giro a giro, autonomía, márgenes de horas obligadas, tráfico en vivo sobre la ruta de moto.',
  'Describe the ride. I’ll research real stops, measure route choices, and show you the pieces before anything is created.': 'Describe la ruta. Investigaré paradas reales, mediré opciones de ruta y te enseñaré las piezas antes de crear nada.',
  'Explore the trip': 'Explorar el viaje',
  'Keep route, change stops': 'Mantener ruta, cambiar paradas',
  'Keep stops, change roads': 'Mantener paradas, cambiar carreteras',
  'Shorten it': 'Acortarla',

  // landing page — Direction C, The Long Way Round (Sep 13, 2026)
  'Tell Roadbook the ride in a sentence. It researches the stops, measures the roads on a motorcycle, grades every day, and then rides the plan with you.':
    'Cuéntale la ruta a Roadbook en una frase. Investiga las paradas, mide las carreteras en moto, califica cada día y luego rueda el plan contigo.',
  'See how it works': 'Ver cómo funciona',
  'Six weeks out': 'Seis semanas antes',
  'The sentence.': 'La frase.',
  '“Five days Missoula to Sturgis, back roads, no tolls, in by four on Friday.” That is the whole brief. The planner narrates while it works — searching places, routing options, checking fuel against your range — because it is doing research, not typing from memory.':
    '«Cinco días de Missoula a Sturgis, carreteras secundarias, sin peajes, llegar antes de las cuatro el viernes». Ese es todo el encargo. El planificador narra mientras trabaja — busca lugares, traza opciones, comprueba el combustible frente a tu autonomía — porque está investigando, no escribiendo de memoria.',
  'The same evening': 'Esa misma tarde',
  'Three ways to do it.': 'Tres formas de hacerlo.',
  'All three cross the Beartooth; they differ on the Bighorns and on how hard Friday works. One is graded A with fifty minutes to spare at the gate. That is the one you send the crew.':
    'Las tres cruzan el Beartooth; se diferencian en los Bighorn y en cuánto aprieta el viernes. Una tiene nota A con cincuenta minutos de margen en la hora obligada. Esa es la que mandas al grupo.',
  'Two weeks out': 'Dos semanas antes',
  'The plan gets a planner.': 'El plan tiene planificador.',
  'A rider drops out. “Re-time everything from Cody.” The Copilot proposes the edits, locks the beds already booked, and shows the delta on every line. Apply, and Thursday is an A again.':
    'Un motorista se baja. «Recalcula todo desde Cody». El Copiloto propone las ediciones, bloquea las camas ya reservadas y enseña el cambio en cada línea. Aplica, y el jueves vuelve a ser una A.',
  'The week of': 'La semana del viaje',
  'The board.': 'El tablero.',
  'Prep is the map-less status board: the trip’s grade with its top issues, bookings, packing, a budget built from the trip’s own nights and miles, and the crew.':
    'Prep es el tablero de estado sin mapa: la nota del viaje con sus problemas principales, reservas, equipaje, un presupuesto hecho con las noches y millas del propio viaje, y el grupo.',
  'Day two': 'Día dos',
  'The Beartooth.': 'El Beartooth.',
  'Ride Mode is full navigation for a bike: course-up chase camera, spoken turns, the posted limit as a sign, fuel range counting down, the next gate’s margin. Miss a stop and the plan follows you.':
    'El Modo Ruta es navegación completa para moto: cámara orientada al rumbo, giros hablados, el límite señalizado como una señal, autonomía en cuenta atrás, el margen de la siguiente hora obligada. Sáltate una parada y el plan te sigue.',
  'Next year': 'El año que viene',
  'The ride gets ridden again.': 'La ruta se vuelve a rodar.',
  'Save the trip as a template and hand it to a friend. Their copy arrives with fresh dates and nothing booked, ready for the AI to change what they like.':
    'Guarda el viaje como plantilla y dásela a un amigo. Su copia llega con fechas nuevas y sin reservas, lista para que la IA cambie lo que quiera.',
  'saved as a template': 'guardado como plantilla',
  'Start a trip from it': 'Empezar un viaje desde ella',
  'beartooth-bighorns-template.json → a friend’s Import': 'beartooth-bighorns-template.json → el Importar de un amigo',

  // legal pages (Sep 13, 2026)
  'Legal': 'Legal',
  'Privacy Policy': 'Política de privacidad',
  'Terms of Service': 'Términos del servicio',
  'Effective and last updated': 'En vigor y actualizado por última vez el',
  'Roadbook is a product of Calaf, Inc.': 'Roadbook es un producto de Calaf, Inc.',
  'By creating an account you agree to the': 'Al crear una cuenta aceptas los',
  'and the': 'y la',

  'Account': 'Cuenta',
  'Sign in': 'Iniciar sesión',
  'Signing in…': 'Iniciando sesión…',
  'Create account': 'Crear cuenta',
  'Create an account': 'Crea una cuenta',
  'Create your account': 'Crea tu cuenta',
  'Creating…': 'Creando…',
  'I already have an account': 'Ya tengo una cuenta',
  'Email': 'Correo',
  'Password': 'Contraseña',
  'New password': 'Contraseña nueva',
  'At least 8 characters': 'Al menos 8 caracteres',
  'Use at least 8 characters.': 'Usa al menos 8 caracteres.',
  'Shown to your crew': 'Visible para tu grupo',
  'Forgot password?': '¿Olvidaste la contraseña?',
  'Reset your password': 'Restablece tu contraseña',
  'Email me a link': 'Envíame un enlace',
  'Sending…': 'Enviando…',
  'Back to sign in': 'Volver a iniciar sesión',
  'Set a new password': 'Elige una contraseña nueva',
  'Save password': 'Guardar contraseña',
  'Saving…': 'Guardando…',
  'Password changed.': 'Contraseña cambiada.',
  'You followed a reset link. Pick a new password and you are back in.':
    'Has seguido un enlace de restablecimiento. Elige una contraseña nueva y vuelves a entrar.',
  'If that address has an account, a reset link is on its way.':
    'Si esa dirección tiene cuenta, el enlace de restablecimiento va en camino.',
  'Account created. Check your email for the confirmation link, then sign in.':
    'Cuenta creada. Busca el enlace de confirmación en tu correo y luego inicia sesión.',
  'Check your email to verify the address. If this device was already sharing a trip, the link will ask you to finish with a password.':
    'Revisa tu correo para verificar la dirección. Si este dispositivo ya compartía un viaje, el enlace te pedirá terminar con una contraseña.',
  'Finish your account': 'Termina de crear tu cuenta',
  'Your email is verified. Choose a password to finish protecting this account.':
    'Tu correo está verificado. Elige una contraseña para terminar de proteger esta cuenta.',
  'Account ready.': 'Cuenta lista.',
  'Accounts are not configured on this build.': 'Las cuentas no están configuradas en esta versión.',
  'That email and password do not match.': 'Ese correo y esa contraseña no coinciden.',
  'There is already an account on that email — sign in instead.': 'Ya existe una cuenta con ese correo — inicia sesión.',
  'That does not look like an email address.': 'Eso no parece una dirección de correo válida.',
  'Too many emails just went out. Wait a few minutes and try again.': 'Se enviaron demasiados correos. Espera unos minutos e inténtalo de nuevo.',
  'Account upgrades are not enabled yet. Try again in a moment.': 'La conversión de cuentas aún no está activada. Inténtalo de nuevo en un momento.',
  'That account link has expired. Start again from Create account.': 'Ese enlace de cuenta venció. Empieza de nuevo desde Crear una cuenta.',
  'No connection. Your trips are safe on this device — try again when you have signal.': 'Sin conexión. Tus viajes están seguros en este dispositivo — inténtalo cuando tengas señal.',
  'Your trips live on this device. An account gives them a second home — delete the app, change phones, or lose the bike bag, and the roadbook is still there.':
    'Tus viajes viven en este dispositivo. Una cuenta les da un segundo hogar — borra la app, cambia de móvil o pierde la alforja, y el roadbook sigue ahí.',
  'Continue without an account →': 'Continuar sin cuenta →',
  'Everything works offline on this device. You can create an account later and your trips come with you.':
    'Todo funciona sin conexión en este dispositivo. Puedes crear una cuenta más tarde y tus viajes se van contigo.',
  'No account. Your trips live only on this device — deleting the app, clearing the browser, or losing the phone loses them.':
    'Sin cuenta. Tus viajes viven solo en este dispositivo — borrar la app, limpiar el navegador o perder el móvil los pierde.',
  'Back up now': 'Copiar ahora',
  'Backing up…': 'Copiando…',
  'Not backed up yet.': 'Aún sin copia de seguridad.',
  'trip backed up': 'viaje respaldado',
  'trips backed up': 'viajes respaldados',
  'Backup failed — it will retry. Your trips are safe on this device.':
    'Falló la copia — se reintentará. Tus viajes están a salvo en este dispositivo.',
  'Signing out leaves every trip on this device. Sign back in on any phone to get them all.':
    'Cerrar sesión deja todos los viajes en este dispositivo. Vuelve a entrar en cualquier móvil para recuperarlos.',
  'just now': 'ahora mismo',
  'min ago': 'min',
};

export function useT() {
  const { lang } = useSettings();
  return (s) => (lang === 'es' ? (ES[s] ?? s) : s);
}

// ---- units ----
// Imperial is the app's native unit system (the data is written in mi/°F).
// Metric converts at the last moment, display-only.

const MI_KM = 1.609344;

export function useUnits() {
  const { units } = useSettings();
  const metric = units === 'metric';
  return {
    metric,
    // distances
    mi: (n, digits = 0) => (n == null || Number.isNaN(n) ? '—'
      : metric ? `${(n * MI_KM).toFixed(digits)} km` : `${Number(n).toFixed(digits)} mi`),
    miNum: (n) => (metric ? Math.round(n * MI_KM) : Math.round(n)),
    miUnit: metric ? 'km' : 'mi',
    // temperature (data is °F)
    temp: (f) => (f == null || Number.isNaN(f) ? '—'
      : metric ? `${Math.round(((f - 32) * 5) / 9)}°` : `${Math.round(f)}°`),
    tempUnit: metric ? '°C' : '°F',
    // speed (data is mph)
    speed: (mph) => (mph == null || Number.isNaN(mph) ? '—'
      : metric ? `${Math.round(mph * MI_KM)} km/h` : `${Math.round(mph)} mph`),
  };
}

// Convert the units that appear inside prose/engine sentences. Conservative:
// only "N mi", "N-mi", "N mph", "N ft", "N°F" style tokens; road numbers
// (US-14, I-90) and times are untouched.
function metricizeText(s) {
  return s
    .replace(/(\d[\d,]*(?:\.\d+)?)([ -])mi\b/g, (_, n, sep) => `${Math.round(parseFloat(n.replace(/,/g, '')) * MI_KM)}${sep}km`)
    .replace(/(\d[\d,]*(?:\.\d+)?) ?mph\b/g, (_, n) => `${Math.round(parseFloat(n.replace(/,/g, '')) * MI_KM)} km/h`)
    .replace(/(\d[\d,]*(?:\.\d+)?)[ -]?ft\b/g, (_, n) => `${Math.round(parseFloat(n.replace(/,/g, '')) * 0.3048).toLocaleString('en-US')} m`)
    .replace(/(\d+(?:\.\d+)?)°F\b/g, (_, n) => `${Math.round(((parseFloat(n) - 32) * 5) / 9)}°C`)
    .replace(/(\d[\d,]*(?:\.\d+)?) miles\b/g, (_, n) => `${Math.round(parseFloat(n.replace(/,/g, '')) * MI_KM)} km`)
    .replace(/(\d[\d,]*(?:\.\d+)?) millas\b/g, (_, n) => `${Math.round(parseFloat(n.replace(/,/g, '')) * MI_KM)} km`);
}

// Trip-content translator. Resolution order lives in i18n/resolve.js; the trip's
// own cache wins, so a translated AI-generated trip needs no code change.
export function useTT() {
  const { lang, units } = useSettings();
  // Optional on purpose: tt() is also used above the trip provider in tests and
  // in chrome-only contexts, where there is simply no cache to consult.
  const tripCache = useContext(TripContext)?.state?.trip?.i18n?.[lang];
  return (s) => {
    if (s == null || typeof s !== 'string') return s;
    let out = resolveContent(s, lang, tripCache);
    // a handful of strings are both chrome and content (phase names, weather
    // conditions), so fall through to the chrome dictionary before giving up
    if (out === s && lang !== 'en') out = ES[s] ?? out;
    if (units === 'metric') out = metricizeText(out);
    return out;
  };
}
