#!/usr/bin/env node
// Builds src/data/landingFrame.js — the landing page's Ride Mode frame from
// data we may ship: OpenStreetMap streets, water, parks and named places
// (ODbL — attributed on the page) around the bike's position on the router's
// real US-212 out of Red Lodge (src/data/landingRoute.js). The page renders
// this as SVG in the Dark basemap's palette under Ride Mode's camera, so a
// landing visit costs zero map calls and ships no Mapbox content.
//
//   node tools/landing-frame.mjs            # fetches Overpass, writes the file
//   node tools/landing-frame.mjs osm.json   # reuse a saved Overpass response
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { LANDING_ROUTE, LANDING_PUCK } from '../src/data/landingRoute.js';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const BBOX = '45.150,-109.280,45.205,-109.220';
const QUERY = `[out:json][timeout:60];(way["highway"](${BBOX});way["waterway"](${BBOX});way["leisure"="park"](${BBOX});way["natural"="water"](${BBOX});node["name"]["amenity"](${BBOX});node["name"]["tourism"](${BBOX});node["name"]["leisure"](${BBOX});way["name"]["amenity"](${BBOX});way["name"]["tourism"](${BBOX});way["name"]["leisure"](${BBOX}););out body;>;out skel qt;`;

async function load() {
  const cached = process.argv[2];
  if (cached) return JSON.parse(readFileSync(cached, 'utf8'));
  const res = await fetch('https://overpass-api.de/api/interpreter', { method: 'POST', body: new URLSearchParams({ data: QUERY }) });
  if (!res.ok) throw new Error(`overpass ${res.status}`);
  return res.json();
}

const R = 6371008.8;
const puck = LANDING_ROUTE[LANDING_PUCK];
const next = LANDING_ROUTE[Math.min(LANDING_PUCK + 3, LANDING_ROUTE.length - 1)];
const p = Math.PI / 180;
const kx = Math.cos(puck[1] * p);
// local metres east/north of the bike
const toM = ([lng, lat]) => [(lng - puck[0]) * p * R * kx, (lat - puck[1]) * p * R];
const [nx, ny] = toM(next);
const heading = (Math.atan2(nx, ny) / p + 360) % 360; // clockwise from north
const ch = Math.cos(heading * p), sh = Math.sin(heading * p);
// course-up: the heading points to +y (ahead)
const frame = (ll) => { const [x, y] = toM(ll); return [Math.round(x * ch - y * sh), Math.round(x * sh + y * ch)]; };
// what the camera can see: a generous ground rectangle around the bike
const IN = ([x, y]) => x > -1400 && x < 1400 && y > -600 && y < 3200;

const d = await load();
const nodes = new Map(d.elements.filter((e) => e.type === 'node').map((n) => [n.id, n]));
const ways = d.elements.filter((e) => e.type === 'way');
const coordsOf = (w) => w.nodes.map((id) => nodes.get(id)).filter(Boolean).map((n) => frame([n.lon, n.lat]));
const thin = (pts) => pts.filter((pt, i, a) => i === 0 || i === a.length - 1 || Math.hypot(pt[0] - a[i - 1][0], pt[1] - a[i - 1][1]) > 4);

const ROAD_KIND = { motorway: 'primary', trunk: 'primary', primary: 'primary', secondary: 'secondary', tertiary: 'secondary', unclassified: 'street', residential: 'street', living_street: 'street', service: 'service' };
const roads = [], water = [], parks = [], pois = [];
for (const w of ways) {
  const t = w.tags ?? {};
  const pts = coordsOf(w);
  if (pts.length < 2 || !pts.some(IN)) continue;
  if (t.highway && ROAD_KIND[t.highway]) roads.push({ k: ROAD_KIND[t.highway], n: t.name ?? null, p: thin(pts) });
  else if (t.waterway === 'river' || t.waterway === 'stream') water.push({ k: 'line', n: t.name ?? null, p: thin(pts) });
  else if (t.natural === 'water') water.push({ k: 'poly', p: thin(pts) });
  else if (t.leisure === 'park') parks.push({ n: t.name ?? null, p: thin(pts) });
  if (t.name && (t.amenity || t.tourism || t.leisure)) {
    const c = pts.reduce((a, q) => [a[0] + q[0] / pts.length, a[1] + q[1] / pts.length], [0, 0]);
    pois.push({ n: t.name, k: t.tourism ? 'lodging' : t.leisure ? 'park' : t.amenity, x: Math.round(c[0]), y: Math.round(c[1]) });
  }
}
for (const n of nodes.values()) {
  const t = n.tags ?? {};
  if (!t.name || !(t.amenity || t.tourism || t.leisure)) continue;
  const [x, y] = frame([n.lon, n.lat]);
  if (IN([x, y])) pois.push({ n: t.name, k: t.tourism ? 'lodging' : t.leisure ? 'park' : t.amenity, x, y });
}
// the sort the basemap makes at this zoom: lodging, food and parks near the road first
const RANK = { lodging: 0, park: 1, restaurant: 2, cafe: 2, bar: 2, pub: 2, fast_food: 3 };
const dist = (q) => Math.hypot(q.x, q.y);
const kept = pois.filter((q) => IN([q.x, q.y]) && (q.k in RANK)).sort((a, b) => (RANK[a.k] - RANK[b.k]) || (dist(a) - dist(b)));
// no two labels within 120 m of each other, at most ten on the frame
const shown = [];
for (const q of kept) { if (shown.length < 10 && !shown.some((s) => Math.hypot(s.x - q.x, s.y - q.y) < 120)) shown.push(q); }

const route = LANDING_ROUTE.map(frame);
const out = `// GENERATED by tools/landing-frame.mjs (${new Date().toISOString().slice(0, 10)}) — do not hand-edit.
// The landing page's Ride Mode frame from OpenStreetMap (© OpenStreetMap
// contributors, ODbL) around the bike on the router's US-212 out of Red Lodge:
// local metres, course-up (+y is ahead), origin at the bike. Rendered as SVG
// in the Dark basemap's palette so a visit costs zero map calls and ships no
// Mapbox content.
export const FRAME_HEADING = ${heading.toFixed(1)};
export const FRAME_ROADS = ${JSON.stringify(roads)};
export const FRAME_WATER = ${JSON.stringify(water)};
export const FRAME_PARKS = ${JSON.stringify(parks)};
export const FRAME_POIS = ${JSON.stringify(shown)};
export const FRAME_ROUTE = ${JSON.stringify(route)};
export const FRAME_PUCK = ${LANDING_PUCK};
`;
writeFileSync(`${ROOT}src/data/landingFrame.js`, out);
console.log(`heading ${heading.toFixed(1)}° · ${roads.length} roads · ${water.length} water · ${parks.length} parks · ${shown.length} places: ${shown.map((q) => q.n).join(' | ')} · ${Math.round(out.length / 1024)} KB`);
